### ISSUE TITLE
env.sample

### ISSUE THREAD

**Issue by niamrox** [fireyy/piper#10]
cp: env.sample: No such file or directory

**Comment by fireyy** [comment]
You must enter the folder

```
cd piper
cp env.sample .env
```

**Comment by niamrox** [comment]
Its not working, cp: env.sample: No such file or directory
Check Screenshot here 
https://www.dropbox.com/s/rternsw5cc5b5uw/Screenshot%202018-03-07%2020.49.23.png?dl=0

**Comment by fireyy** [comment]
You install piper as an npm package, bu it isn’t. The npm package named piper is not mine. You can clone the project and try again.

**Comment by fireyy** [comment]
Also you can try my another project [vue-page-designer](https://github.com/fireyy/vue-page-designer)

**Comment by niamrox** [comment]
Hi,

Figure out the issue. But still did not able to install properly. Here is the error log. I have installed sequelize but still not working.

Please help and thanks in advance. Like your this version and really nice.

Error: Cannot find module '/Volumes/Storage/devil/market/docroot/builder/node_modules/piper/node_modules/.bin/sequelize'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! piper@1.0.5 db:update: `node node_modules/.bin/sequelize db:migrate --config=config/db.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the piper@1.0.5 db:update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/niamulhasan/.npm/_logs/2018-03-07T15_06_19_790Z-debug.log

**Comment by fireyy** [comment]
New install, no need to run db:update
