### ISSUE TITLE
How to use sqlite as db.

### ISSUE THREAD

**Issue by liamlangli** [fireyy/piper#6]
thats all.

**Comment by fireyy** [comment]
See [Sequelizejs: Setting up a connection](http://docs.sequelizejs.com/manual/installation/getting-started.html#setting-up-a-connection) for more detail.

**Comment by fireyy** [comment]
and set `DATABASE_DIALECT`  to `sqlite`

**Comment by liamlangli** [comment]
got it, i have seen what you have done, good work.
