### ISSUE TITLE
sql在初始导入时报错

### ISSUE THREAD

**Issue by WilliamsGLEE** [fireyy/piper#9]
![image](https://user-images.githubusercontent.com/13540206/33511886-66ee8e56-d75f-11e7-80d4-5b71c0d2ba99.png)

你好，sql在初始导入时报错，你的repo上是否有sql的配置没有更新？

**Comment by fireyy** [comment]
手动创建一个空的 `piper` 数据库，然后再执行程序

**Comment by WilliamsGLEE** [comment]
已然这样做，只成功的创建出来一个表SequelizeMeta

**Comment by WilliamsGLEE** [comment]
错误截图就在这时发生的。

**Comment by fireyy** [comment]
麻烦提供一下完整的截图，包括你输入的命令
